import { Link } from "react-router-dom";
import { Pill } from "lucide-react";
import { CATEGORIES } from "../lib/categories";

export function Footer() {
  return (
    <footer className="border-t border-slate-200 bg-slate-50">
      <div className="mx-auto max-w-6xl px-4 py-10">
        <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
          <div>
            <div className="flex items-center gap-2">
              <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-teal-600 text-white">
                <Pill className="h-4 w-4" />
              </span>
              <span className="font-display text-lg font-bold text-slate-900">PharmaAI</span>
            </div>
            <p className="mt-3 text-sm text-slate-500">
              Everyday OTC &amp; wellness essentials, with suggestions based on what similar shoppers buy.
            </p>
          </div>

          <div>
            <h3 className="font-display text-sm font-semibold text-slate-900">Shop</h3>
            <ul className="mt-3 space-y-2 text-sm text-slate-500">
              {CATEGORIES.map((c) => (
                <li key={c}>
                  <Link to={`/shop?category=${encodeURIComponent(c)}`} className="hover:text-teal-700">
                    {c}
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          <div>
            <h3 className="font-display text-sm font-semibold text-slate-900">How it works</h3>
            <p className="mt-3 text-sm text-slate-500">
              Browse OTC essentials, read FDA-sourced product info, and see picks that are
              "popular with similar shoppers" or "frequently bought together" — generated by a
              content-based recommender, not a pharmacist.
            </p>
          </div>

          <div>
            <h3 className="font-display text-sm font-semibold text-slate-900">Good to know</h3>
            <ul className="mt-3 space-y-2 text-sm text-slate-500">
              <li>Product data sourced from the FDA openFDA database.</li>
              <li>Users, orders, and prices are synthetic demo data — prices are illustrative only.</li>
              <li>This site provides product information, not medical advice.</li>
            </ul>
          </div>
        </div>

        <div className="mt-10 border-t border-slate-200 pt-6 text-xs text-slate-400">
          <p>
            PharmaAI is a local demo. There is no real authentication, no real payment processing, and
            nothing here is medical advice — for guidance on medications, talk to a pharmacist or doctor.
          </p>
          <p className="mt-2">© 2026 PharmaAI — v1 local demo.</p>
        </div>
      </div>
    </footer>
  );
}
